'use strict';

const ROLE_RANK = { LEADER: 4, OFFICER: 3, MEMBER: 1 };

const ROLE_COLOR = { LEADER: 0xFFD700, OFFICER: 0x55CCFF, MEMBER: 0xAAAAAA };

const DEFAULT_PERMISSIONS = {
	LEADER: ['INVITE', 'KICK', 'PROMOTE_DEMOTE', 'EDIT_CLAN_INFO', 'MANAGE_HOMES', 'DISBAND', 'SEND_OFFICER_CHAT'],
	OFFICER: ['INVITE', 'KICK', 'SEND_OFFICER_CHAT', 'MANAGE_HOMES'],
	MEMBER: [],
};

module.exports = { ROLE_RANK, ROLE_COLOR, DEFAULT_PERMISSIONS };
